spring:
  application:
    name: service-a
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: true
        root: dev
#        metadata:
#          instanceId: ${spring.application.name}:${java.rmi.server.hostname}:${server.port} #自定义instanceId
server:
  port: 20101

gray:
  client:
    instance:
      grayEnroll: true #是否在启动后自动注册成灰度实例
    serverUrl: http://localhost:20202 #灰度服务端的url