spring:
  application:
    name: api-gateway
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: true
        root: dev
#        metadata:
#          instanceId: ${spring.application.name}:${java.rmi.server.hostname}:${server.port} #自定义instanceId

server:
  port: 20301

ribbon:
#    ReadTimeout: 30000
#    ConnectTimeout: 30000

zuul:
  prefix: /gateway #为zuul设置一个公共的前缀
#  routes:
#    eureka-client: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
#      path: /client/** #匹配/techouse/usersystem/** 均路由到cloud-client
#      serviceId: eureka-client #指定路由到的serviceId
gray:
  client:
    server-url: http://localhost:20202 #灰度服务端的url
    instance:
      use-multi-version: false