spring:
  application:
    name: api-gateway
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    stream:
      bindings:
        GrayEventInput:
          group: zuul
          destination: gray_event
          consumer:
            concurrency: 1 #并发数
        #            max-attempts: 1
      #        GrayEventOutput:
      #          destination: gray-event
      rabbit:
        bindings:
          GrayEventInput:
            consumer:
              maxConcurrency: 1 #并发数
              #              prefetch: 1 #从mq一次获取消息的数量
              #              requeueRejected: true #spring cloud stream 如果出现异常， 是否需要重新投递消息， false表示丢弃。  也有相应的Exception， true-MessageRejectedWhileStoppingException false-AmqpRejectAndDontRequeueException
              #              auto-bind-dlq: true
              acknowledgeMode: AUTO
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
server:
  port: 20401
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/

ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 30000
    eureka:
        enabled: true
hystrix:
  threadpool:
    # 这是默认的配置
    default:
      coreSize: 10
      maxQueueSize: 200
      queueSizeRejectionThreshold: 2
  command:
    service-a:
      circuitBreaker:
        enabled: true
        forceOpen: true
gray:
  enabled: true
  hystrix:
    enabled: true
  server:
    url: http://localhost:20202
    loadbalanced: false
  client:
    runenv: web
    serviceUpdateIntervalTimerInMs: 5000
    serviceInitializeDelayTimeInMs: 10000
  holdout-server:
    enabled: true
  request:
    track:
      definitionsUpdateIntervalTimerInMs: 5000
      definitionsInitializeDelayTimeInMs: 10000
      web:
        track-definitions:
          #          - name: HttpIP
          #          - name: HttpMethod
          #          - name: HttpURI
          #          - name: HttpReceive
#          - name: HttpHeader
        #          - name: HttpParameter
        #            value: version,test
        path-patterns: /*
  load:
    enabled: true