spring:
  #  main:
  #      allow-bean-definition-overriding: true
  application:
    name: service-b
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    stream:
      bindings:
        GrayEventInput:
          #          contentType: application/x-java-serialized-object
          group: service-a
          destination: gray_event
          consumer:
            concurrency: 1 #并发数
        #            max-attempts: 1
      #        GrayEventOutput:
      #          destination: gray-event
      rabbit:
        bindings:
          GrayEventInput:
            consumer:
              maxConcurrency: 1 #并发数
              #              prefetch: 1 #从mq一次获取消息的数量
              #              requeueRejected: true #spring cloud stream 如果出现异常， 是否需要重新投递消息， false表示丢弃。  也有相应的Exception， true-MessageRejectedWhileStoppingException false-AmqpRejectAndDontRequeueException
              #              auto-bind-dlq: true
              acknowledgeMode: AUTO
#              acknowledgeMode: MANUAL
server:
  port: 20102
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    region: sh
    availability-zones:
      sh: xuhui,gray
    serviceUrl:
      #      defaultZone: http://localhost:20001/eureka/
      xuhui: http://localhost:20001/eureka/
      gray: http://localhost:20001/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
#    initial-status: starting
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 100


gray:
  mock:
    enabled: true

  enabled: true
  hystrix:
    enabled: true
  server:
    url: http://gray-Server
    loadbalanced: true
    retryable: true
    retryNumberOfRetries: 3
  client:
    event:
      longpolling: 60000
    runenv: web
    infosUpdateIntervalTimerInMs: 0
    infosInitializeDelayTimeInMs: 10000
    instance:
      grayEnroll: false
      grayEnrollDealyTimeInMs: 20000
  holdoutServer:
    enabled: true
    services:
      "service-a": starting
  request:
    track:
      enabled: true
      trackType: web
      definitionsUpdateIntervalTimerInMs: 10000
      definitionsInitializeDelayTimeInMs: 10000
      web:
        track-definitions:
          #          - name: HttpIP
          #          - name: HttpMethod
          #          - name: HttpURI
          - name: HttpReceive
        #          - name: HttpHeader
        #            value: test,test-mm
        #          - name: HttpParameter
        #            value: version,test
        path-patterns: /*
        exclude-path-patterns: /test/*
#  load:
#    enabled: true
#    gray-instances:
#      - serviceId: service-a
#        instance-id: service-a:20104
#        policy-definitions:
#          - policyId: policy-1
#            alias: policy-1
#            list:
#              - id: decision-1
#                name: HttpHeader
#                infos:
#                  compare-mode: EQUAL
#                  header: _graytrack_header__test
#                  values: true
#  client:
#    instance:
#      grayEnroll: false #是否在启动后自动注册成灰度实例
logging:
  level:
    cn:
      springcloud:
        gray: debug
#    serverUrl: http://localhost:20202 #灰度服务端的url