spring:
  application:
    name: service-a
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 20103
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    region: sh
#    availability-zones:
#      sh: xuhui
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/
#      xuhui: http://localhost:20001/eureka/
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
#    metadata-map:
#      zone: gray3
#      instanceId: s
    initial-status: up
