spring:
  application:
    name: api-gateway
server:
  port: 20301
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20001/eureka/

ribbon:
#    ReadTimeout: 30000
#    ConnectTimeout: 30000
    eureka:
        enabled: true
zuul:
  prefix: /gateway #为zuul设置一个公共的前缀
#  routes:
#    eureka-client: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
#      path: /client/** #匹配/techouse/usersystem/** 均路由到cloud-client
#      serviceId: eureka-client #指定路由到的serviceId
gray:
  client:
    server-url: http://localhost:20202 #灰度服务端的url